### ISSUE TITLE
Todo for end of October 

### ISSUE THREAD

**Issue by richardwsong** [brainhack-vandy/brainhack-vandy.github.io#1]
- [x] Use template to create bare-bone website. Incorporate what is Brainhack, faq, code of conduct, and tentative schedule (1/24-1/26). You can use last year's descriptions to start 
- [x] Most important: Create an "Interested in pitching a project" tab. 
- [x] In "Interested in pitching project" tab, include description for what pitching a project means. Link thumbnail to youtube video about how to pitch a project. Include link to last year's projects on github. Link google form for project pitch interest form

**Comment by rgbayrak** [comment]
- [ ] add a link to our youtube channel
