### ISSUE TITLE
All tabs

### ISSUE THREAD

**Issue by rgbayrak** [brainhack-vandy/brainhack-vandy.github.io#6]
tabs:
- [x] (in the landing page above the location section) Sponsors (titled "2024 Sponsors", we will replace these with this years when we have them and archive the old ones)  #12 
- [x]  Schedule (this can be retrieved from meeting notes) #13 
- [x]  Projects #8 
- [x]  Educationals #9 
- [x]  FAQs #11 
- [x]  Team (add all organizers and volunteers) #22

**Comment by rgbayrak** [comment]
@shansitads can we get the starred tabs done this week?

**Comment by shansitads** [comment]
All tabs had been completed for Brainhack 2025 so this issue is being closed.
